import React from 'react';
import Head from 'next/head';
import { Card, CardActionArea, CardContent, CardMedia, Grid, Typography } from '@mui/material';
import Link from 'next/link';
import Slider from '../components/Slider';
import ProductData from '../components/ProductData';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      <Typography variant="h4">Product</Typography>
      <Grid container rowGap={2} columnSpacing={2}>
        {ProductData.map((product) => (
          <Grid key={product.id} item xs={12} sm={6} md={4} lg={3}>
            <Card>
              <Link href={{ pathname: '/product/[product-details]', query: { 'product-details': product.id } }}>
                <CardActionArea>
                  <CardMedia
                    component="img"
                    height="34%"
                    image={product.img.src}
                    alt={product.img.src}
                  />
                  <CardContent>
                    <Typography gutterBottom variant="h4" component="div" />
                    <Typography variant="h5">
                      {product.Title}
                    </Typography>
                    <Typography variant="h6">
                      {product.Price}
                    </Typography>
                    <Typography variant="p">
                      {product.Des}
                    </Typography>
                  </CardContent>
                </CardActionArea>
              </Link>
            </Card>
          </Grid>

        ))}
      </Grid>
    </>
  );
}
